close all;
clear variables;

%% Preliminaries
studyID='24.chdi.02';
project_dir='Z:\All_Staff\25.chdi.02\';
google_doc=fullfile(project_dir,"google_sheets","25.chdi.02_scansheet_20260422.tsv");
cleaned_google_doc_path=fullfile(project_dir,"google_sheets","Edited_GoogleSheetQ111_2026_04_22.txt");
statSaveDir=fullfile(project_dir,'12Month_Q111_20260422');

dataframe_path=fullfile(project_dir,"25.chdi.02_DataFrame_20260422.txt");
config_file='';
polished_sheets=fullfile(project_dir,'polished_sheets'); %where the polished sheets will be saved 
project_research_archive{1}=fullfile('A:/',studyID,'research');
atlas_ontology_path=fullfile(getenv("WORKSTATION_HOME"),'static_data','atlas','symmetric15um','labels','RCCF','symmetric15um_RCCF_labels_lookup.txt'); 

studyParams={
  studyID,...
  statSaveDir,...
  'configFile',config_file,...
  'googleDocPath',google_doc,...
  'cleanedGoogleDocPath',cleaned_google_doc_path...
  'dataframePath',dataframe_path...
  'overrideLabelLUT',atlas_ontology_path,...
  'researchArchivePath',project_research_archive,...
  'polishedSheetPath',polished_sheets,...
  'assumeNLSAM',true ...
  'allowMissing',true};

civm_diffusion_stats(studyParams{:});