close all;
clear variables;

%% Preliminaries
studyID='20.5xFAD.01';
project_dir='Z:\All_Staff\20.5xFAD.01\';
google_doc="Z:\All_Staff\20.5xFAD.01\google_sheet_captures\20.5XFAD.01_Phase2Sheet_20260508.tsv";
cleaned_google_doc_path="Z:\All_Staff\20.5xFAD.01\google_sheet_captures\Edited_GoogleSheet_20260508_Phase2.txt";
statSaveDir=fullfile(project_dir,'Analysis_20260513_SAMBA');

dataframe_path="Z:\All_Staff\20.5xFAD.01\20.5xFAD.01_DataFrame_20260513_SAMBA_BXD60.txt";
config_file='';
polished_sheets=fullfile(project_dir,'polished_SAMBA_sheets'); %where the polished sheets will be saved 

project_research_archive{1}=fullfile('A:/20.5xFAD.02/research');

atlas_ontology_path=fullfile(getenv("WORKSTATION_HOME"),'static_data','atlas','symmetric15um','labels','RCCF','symmetric15um_RCCF_labels_lookup.txt'); 

default_scalarContrast=struct;
default_scalarContrast(1).Name={'Non_Erode'}; 
default_scalarContrast(1).Column={'stat_path'};
default_scalarContrast(1).List=list2cell("volume_mm3 volume_fraction fa_mean ad_mean md_mean rd_mean");

studyParams={
  studyID,...
  statSaveDir,...
  'configFile',config_file,...
  'dataframePath',dataframe_path,...
  'googleDocPath',google_doc,...
  'cleanedGoogleDocPath',cleaned_google_doc_path,...
  'overrideLabelLUT',atlas_ontology_path,...
  'researchArchivePath',project_research_archive,...
  'polishedSheetPath',polished_sheets,...
  'suffix','GMDT',...
  'allowMissing',false,...
  'assumeNLSAM', true,...
  'analysisPipelineType', list2cell('Scalar'),...
  'scalarContrastMetrics',default_scalarContrast,...
  'alternative_statsheet_dir','B:\20.5xfad.02\stats\SAMBA_stats_GMDT\2026-05-12'};

civm_diffusion_stats(studyParams{:});
