close all;
clear variables;

%% Preliminaries
studyID='20.5xFAD.01';
project_dir='Z:\All_Staff\20.5xFAD.01\';
google_doc="Z:\All_Staff\20.5xFAD.01\google_sheet_captures\20.5XFAD.01_Phase1Sheet_2026_05_05.tsv";
cleaned_google_doc_path="Z:\All_Staff\20.5xFAD.01\google_sheet_captures\Edited_GoogleSheet_20260506.txt";
statSaveDir=fullfile(project_dir,'Analysis_20260513_SAMBA_BXD77-Testing');

dataframe_path="Z:\All_Staff\20.5xFAD.01\20.5xFAD.01_DataFrame_20260513_SAMBA_BXD77.txt";
config_file='';
polished_sheets=fullfile(project_dir,'polished_SAMBA_sheets-test'); %where the polished sheets will be saved 

project_research_archive{1}=fullfile('A:/20.5xFAD.02/research');

atlas_ontology_path=fullfile(getenv("WORKSTATION_HOME"),'static_data','atlas','symmetric15um','labels','RCCF','symmetric15um_RCCF_labels_lookup.txt'); 

studyParams={
  studyID,...
  statSaveDir,...
  'configFile',config_file,...
  'dataframePath',dataframe_path,...
  'googleDocPath',google_doc,...
  'cleanedGoogleDocPath',cleaned_google_doc_path,...
  'overrideLabelLUT',atlas_ontology_path,...
  'researchArchivePath',project_research_archive,...
  'polishedSheetPath',polished_sheets,...
  'suffix','GMDT',...
  'allowMissing',false,...
  'assumeNLSAM', true,...
  'analysisPipelineType', list2cell('Scalar'),...
  'alternative_statsheet_dir','B:\20.5xfad.02\stats\SAMBA_stats_GMDT\2026-05-12'};

civm_diffusion_stats(studyParams{:});
