close all;
clear variables;

%% Preliminaries
studyID='21.QA94TAgilent.01';
project_dir='B:\20.5xfad.02\QA_Studies_Scalar_Stats\';
google_doc="B:\20.5xfad.02\21QA94TAgilent_20260215_WithWyattNotes.txt";
% googledata=civm_read_table(google_doc);
% googledata.Age=repmat(90,height(googledata),1);
% googledata.Strain=repmat('B6',height(googledata),1);
% 
% civm_write_table(googledata,google_doc)

cleaned_google_doc_path='B:\20.5xfad.02\Edited_21QA94TAgilent_20260215_WithWyattNotes.txt';
statSaveDir=fullfile(project_dir,'Agilent_v_MRS1');

dataframe_path=fullfile(statSaveDir, '21QA94TAgilent_20260215_WithWyattNotes_AvM1.txt');
config_file='';
polished_sheets=fullfile(project_dir,'polished_sheets'); %where the polished sheets will be saved 
project_research_archive{1}=fullfile('A:/',studyID,'research');
atlas_ontology_path=fullfile(getenv("WORKSTATION_HOME"),'static_data','atlas','symmetric15um','labels','RCCF','symmetric15um_RCCF_labels_lookup.txt'); 

studyParams={
  studyID,...
  statSaveDir,...
  'configFile',config_file,...
  'googleDocPath',google_doc,...
  'cleanedGoogleDocPath',cleaned_google_doc_path,...
  'dataframePath',dataframe_path,...
  'overrideLabelLUT',atlas_ontology_path,...
  'researchArchivePath',project_research_archive,...
  'polishedSheetPath',polished_sheets,...
  'suffix','batchQA',...
};

civm_diffusion_stats(studyParams{:});

%% Preliminaries
studyID='21.QA94TAgilent.01';
project_dir='B:\20.5xfad.02\QA_Studies_Scalar_Stats\';
google_doc="B:\20.5xfad.02\21QA94TAgilent_20260215_WithWyattNotes.txt";
cleaned_google_doc_path='B:\20.5xfad.02\Edited_21QA94TAgilent_20260215_WithWyattNotes.txt';
statSaveDir=fullfile(project_dir,'PCI_AMP');

dataframe_path=fullfile(statSaveDir, '21QA94TAgilent_20260215_WithWyattNotes.txt');
config_file='';
polished_sheets=fullfile(project_dir,'polished_sheets'); %where the polished sheets will be saved 
project_research_archive{1}=fullfile('A:/',studyID,'research');
atlas_ontology_path=fullfile(getenv("WORKSTATION_HOME"),'static_data','atlas','symmetric15um','labels','RCCF','symmetric15um_RCCF_labels_lookup.txt'); 

studyParams={
  studyID,...
  statSaveDir,...
  'configFile',config_file,...
  'googleDocPath',google_doc,...
  'cleanedGoogleDocPath',cleaned_google_doc_path,...
  'dataframePath',dataframe_path,...
  'overrideLabelLUT',atlas_ontology_path,...
  'researchArchivePath',project_research_archive,...
  'polishedSheetPath',polished_sheets,...
  'suffix','batchQA',...
  'allowMissing',true};

civm_diffusion_stats(studyParams{:});


close all;
clear variables;

%% Preliminaries
studyID='21.QA94TAgilent.01';
project_dir='B:\20.5xfad.02\QA_Studies_Scalar_Stats\';
google_doc="B:\20.5xfad.02\21QA94TAgilent_20260215_WithWyattNotes.txt";
cleaned_google_doc_path='B:\20.5xfad.02\Edited_21QA94TAgilent_20260215_WithWyattNotes.txt';
statSaveDir=fullfile(project_dir,'FSEage');

dataframe_path=fullfile(statSaveDir, '21QA94TAgilent_20260215_WithWyattNotes_FSEage.txt');
config_file='';
polished_sheets=fullfile(project_dir,'polished_sheets'); %where the polished sheets will be saved 
project_research_archive{1}=fullfile('A:/',studyID,'research');
atlas_ontology_path=fullfile(getenv("WORKSTATION_HOME"),'static_data','atlas','symmetric15um','labels','RCCF','symmetric15um_RCCF_labels_lookup.txt'); 

studyParams={
  studyID,...
  statSaveDir,...
  'configFile',config_file,...
  'googleDocPath',google_doc,...
  'cleanedGoogleDocPath',cleaned_google_doc_path,...
  'dataframePath',dataframe_path,...
  'overrideLabelLUT',atlas_ontology_path,...
  'researchArchivePath',project_research_archive,...
  'polishedSheetPath',polished_sheets,...
  'suffix','batchQA',...
  'allowMissing',true};

civm_diffusion_stats(studyParams{:});


%% Preliminaries
studyID='21.QA94TAgilent.01';
project_dir='B:\20.5xfad.02\QA_Studies_Scalar_Stats\';
google_doc="B:\20.5xfad.02\21QA94TAgilent_20260215_WithWyattNotes.txt";
cleaned_google_doc_path='B:\20.5xfad.02\Edited_21QA94TAgilent_20260215_WithWyattNotes.txt';
statSaveDir=fullfile(project_dir,'SEage');

dataframe_path=fullfile(statSaveDir, '21QA94TAgilent_20260215_WithWyattNotes_SEage.txt');
config_file='';
polished_sheets=fullfile(project_dir,'polished_sheets'); %where the polished sheets will be saved 
project_research_archive{1}=fullfile('A:/',studyID,'research');
atlas_ontology_path=fullfile(getenv("WORKSTATION_HOME"),'static_data','atlas','symmetric15um','labels','RCCF','symmetric15um_RCCF_labels_lookup.txt'); 

studyParams={
  studyID,...
  statSaveDir,...
  'configFile',config_file,...
  'googleDocPath',google_doc,...
  'cleanedGoogleDocPath',cleaned_google_doc_path,...
  'dataframePath',dataframe_path,...
  'overrideLabelLUT',atlas_ontology_path,...
  'researchArchivePath',project_research_archive,...
  'polishedSheetPath',polished_sheets,...
  'suffix','batchQA',...
  'allowMissing',true};

civm_diffusion_stats(studyParams{:});